### ISSUE TITLE
Make action to trigger detailed Habit view

### ISSUE THREAD

**Issue by PaoVal** [CMPUT301F21T23/HabitTracker#11]
This issue is related to user story #8 

The user should be able to perform this action on a specific habit. 

The action may be a button click/ a swipe on an item/ a click on an item/ a check-marked item + a button click/ etc...

The action should carry the user to a different UI that displays habit details.

**Comment by zarifmahfuz** [comment]
Work has been done on this issue. When the user clicks on a certain habit in our habits list screen, a new view with more details on the clicked habit is launched. This is show in the following UI mockup: https://github.com/CMPUT301F21T23/HabitTracker/wiki/View-Habit-Details
