### ISSUE TITLE
Edit habitID field of a HabitEvent bug

### ISSUE THREAD

**Issue by johnzhang27** [CMPUT301F21T23/HabitTracker#122]
When you try to edit habitID filed of an existed habit event, more habit event would be added to the event list.
This might be related to how we set up the snapshot listener, need to do more research in the future.

**Comment by PaoVal** [comment]
This bug will be fixed post half-way checkpoint as it is a very specific case that doesn't affect the main functionality

**Comment by johnzhang27** [comment]
HabitID field is no longer needed.
