### ISSUE TITLE
Make action to trigger "edit a Habit" view

### ISSUE THREAD

**Issue by PaoVal** [CMPUT301F21T23/HabitTracker#15]
This issue is related to user story #12 
This might entail listening for the click of a button/ listening for a swipe in a certain direction/ listening for an item click on a list/ etc...

After the action occurs, the user should be transported to #13

**Comment by zarifmahfuz** [comment]
Work has completed for this issue. I created a fragment for editing the details of a certain habit which launches once the user presses the "Edit" button on the Habit View screen. The UI mockup for this can be seen here - https://github.com/CMPUT301F21T23/HabitTracker/wiki/Add-or-Edit-Habit-Mockup
