### ISSUE TITLE
Make some UI for Habit deletion

### ISSUE THREAD

**Issue by PaoVal** [CMPUT301F21T23/HabitTracker#18]
This issue is related to user story #16 

This could be a warning screen of some sort that will indicate "Are you sure you want to delete this habit?"

Or some other UI as discussed in UI and UX planning meeting.

**Comment by zarifmahfuz** [comment]
Work has been completed for this issue. When the user clicks on the "Delete" button of the Habit View screeen, the application will delete that particular habit. The UI mockup for this issue can be seen here - https://github.com/CMPUT301F21T23/HabitTracker/wiki/Add-or-Edit-Habit-Mockup
