### ISSUE TITLE
Research adding photographs - Contact project owner

### ISSUE THREAD

**Issue by PaoVal** [CMPUT301F21T23/HabitTracker#37]
This issue is related to user story #36 

Some points to research include:

- [ ] Ask project owner where is the photograph expected to come from?
  - [x] If the photograph comes from local files, research how to implement this
  - [ ] If the photograph comes from the internet, research how to implement this
- [ ] If the photograph comes from local files, ask project owner if the photograph should remain in the application when the user deleted is from their phone.
- [ ] Research storing image files on firebase.

**Comment by Jie-F** [comment]
Photos can be taken from the device's gallery, or a new photo can be taken from the camera and used. The photo is uploaded to Firebase Storage afterwards and linked to from the Firestore database.
