### ISSUE TITLE
Make UI for Habit Event detail view

### ISSUE THREAD

**Issue by PaoVal** [CMPUT301F21T23/HabitTracker#40]
This issue is related to user story #39 
Should display the information available within the habit event.

This includes but is not restricted to:
* The name of the Habit it is linked to. (Maybe a link to the habit??)
* The comment (if any) attached tot he Habit Event
* Any photos attached to the Habit Event
* etc...

**Comment by johnzhang27** [comment]
Commit#: cd4f16a09bf227c3896420b159c2e9618d88891a
