### ISSUE TITLE
Make UI for feed

### ISSUE THREAD

**Issue by PaoVal** [CMPUT301F21T23/HabitTracker#56]
This issue is related to user story #55 
In feed UI, user should view the habit events of the users the follow. 

Question to ask product owner.
Is this meant to work as a feed? Or is this meant to work as an, ability to view the friend user's profile?
Or is this meant as both?

**Comment by zarifmahfuz** [comment]
All tasks have been completed for this user story. The work completed can been seen by all the issues that have been linked to this issue.
