### ISSUE TITLE
Contact Product owner

### ISSUE THREAD

**Issue by PaoVal** [CMPUT301F21T23/HabitTracker#57]
This issue is related to user story #55 
What information are you allowed to see for those you are NOT friends with?
What should be displayed? How do you want it to be displayed

**Comment by zarifmahfuz** [comment]
We know the answers to the questions asked.

What information are you allowed to see for those you are NOT friends with? Nothing.

What should be displayed? How do you want it to be displayed? The sharing UI mockup posted here (https://github.com/CMPUT301F21T23/HabitTracker/wiki/Habit-Sharing-Mockup) answers this question.
