### ISSUE TITLE
Contact Product Owner regarding geolocation questions

### ISSUE THREAD

**Issue by PaoVal** [CMPUT301F21T23/HabitTracker#59]
This issue is related to user story #58 

Do you request a map?
Should The user be able to see this information on a map?
Or, is text input sufficient?
--> ie. user inputs an address. 
--> We want a link to output the address to Google map.

**Comment by coconutwaters** [comment]
Since the requirements only entail the user being able to record their current location.We only need to be able to capture the current location using a map within the application.
