### ISSUE TITLE
Add display for location in Habit Event UI

### ISSUE THREAD

**Issue by PaoVal** [CMPUT301F21T23/HabitTracker#61]
This issue is related to user story #58 

This might require adding a map depending on the product owner's response in #59

**Comment by johnzhang27** [comment]
The wiki url for issue#61 Add display for location in Habit Event UI
https://github.com/CMPUT301F21T23/HabitTracker/wiki/Habit_Event_Mockup

**Comment by johnzhang27** [comment]
Commit#: cd4f16a09bf227c3896420b159c2e9618d88891a
Commit URL: https://github.com/CMPUT301F21T23/HabitTracker/commit/cd4f16a09bf227c3896420b159c2e9618d88891a
