### ISSUE TITLE
Implement Database Manager class

### ISSUE THREAD

**Issue by zarifmahfuz** [CMPUT301F21T23/HabitTracker#71]
This issue is related to user stories #3 #8 #12 #16 #25 #27 #31 #39 #42 #45 #47 #48 #52 #55 

This class is responsible for performing CRUD operations on Cloud Firestore. This will modularize the code base significantly by removing the need to add the same database code and success/failure listeners in other parts of the application.

This issue is related to all the user requirements posted on the project description.

**Comment by PaoVal** [comment]
Hello all, I believe this issue is stable as of right now. Is it possible to close this? 
(It is in our half-way point check.)

**Comment by zarifmahfuz** [comment]
Yes you can close it

**Comment by johnzhang27** [comment]
> Hello all, I believe this issue is stable as of right now. Is it possible to close this? (It is in our half-way point check.)

The addAllHabitEvents method hasn't been tested yet. We might need to modify it in the future.

**Comment by PaoVal** [comment]
Alright, in that case I suggest we make a new issue for testing this one method
(addAllHabitEvents) and close this thing instead.
