### ISSUE TITLE
Delete User

### ISSUE THREAD

**Issue by PaoVal** [CMPUT301F21T23/HabitTracker#74]
This issue is related to user story #47  and issue #71

User deletion entails:

- [ ] removing the user from the database.
- [ ] removing references to user from:
  - [ ] Followers lists of other users.
  - [ ] FriendRequests lists of other users.

**Comment by PaoVal** [comment]
Hey @zarifmahfuz  is this done?

**Comment by zarifmahfuz** [comment]
@PaoVal not yet

**Comment by PaoVal** [comment]
Since this implementation is quite complex (due to recursively having to delete the user from references to it and sub collections belonging to a user, this will not be implemented for the half-way check point.

**Comment by zarifmahfuz** [comment]
This issue will not be completed since it's not related to any of the requirements.
