### ISSUE TITLE
Comments on the Part 2 Submission

### ISSUE THREAD

**Issue by hamzaMAlvi** [CMPUT301F21T23/HabitTracker#90]
These are the comments by other TA's on the project part 2 submission. You need to address these comments for your next submission.
If necessary make new issues relevant to the comments and link them to this issue (make them a subtask of this issue). If you have any confusion mention me in the comments section of this issue along with the question.

@zarifmahfuz @johnzhang27 @PaoVal @NickSNFK @coconutwaters @Jie-F 

- Excellent job in linking the user stories with issues as well as mentioning story points and risk levels in user story description. For improvement, the risk assessment and user story points can be assigned as a card in the dashboard according to different color schemes and would encourage to complete the halfway checkpoints as well.

- For presentation, wrong CRC cards format. Wrong responsibilities of the classes such as, User cant store/delete a user, rather it keeps a user, and a userController or userManager or userUtility should be able to store/remove a user. We have followed functionality instead of friends functionality. There is no class that could issue follow requests. Classes to communicate with database operations are completely missing.

- UI mockups are mostly consistent and cover most of the requirements. Link mockups with each other or every mockup should start from the homepage. Make things easier for users to understand.

- Good Job in using GitHub. Follow the standard practices for using different tools. Make sure everyone contributes to the project.

**Comment by hamzaMAlvi** [comment]
@zarifmahfuz @johnzhang27 @PaoVal @NickSNFK @coconutwaters @Jie-F 

Marks
Product Backlog: 3/3
OO Analysis: 1/3
UI MockUp & Storyboard: 3/3
Tool Practices: 1/1

**Comment by PaoVal** [comment]
> For improvement, the risk assessment and user story points can be assigned as a card in the dashboard according to different color schemes and would encourage to complete the halfway checkpoints as well.

Added. See tags on user stories

**Comment by PaoVal** [comment]
(Accidentally closed the issue, apologies.)

**Comment by PaoVal** [comment]
These issues have already been addressed, therefore there is no need to keep this parent issue open.
